### ISSUE TITLE
Entrées à ajouter

### ISSUE THREAD

**Issue by allaire** [allaire/builtinsherbrooke#1]
Quelques entrées auxquelles je pense, n'hésitez pas à en créer ou suggérer d'autres!

* ~~Sherweb~~
* ~~PMC Tire~~
* ~~Lubie~~
* ~~ACET~~
* ~~Espace INC~~

**Comment by pcroy** [comment]
- name: Sherweb
  category: company
  url: www.sherweb.com
  description: Le guichet unique pour une variété de solutions infonuagiques, telles que les serveurs et bases de données cloud, l’hébergement Exchange, les applications Office et les outils de collaboration.
  twitter: sherweb
  facebook: sherweb

LOGO : http://www.sherweb.com/fr/a-propos/logos-et-identite-graphique

**Comment by allaire** [comment]
Super merci @pcroy.

Je vais fermer ce issue, SVP ouvrir un nouveau issue pour chaque nouvelle entrée dans la liste avec le format standard du README. 

Merci!
