### ISSUE TITLE
CrowdChat

### ISSUE THREAD

**Issue by kmichaud** [allaire/builtinsherbrooke#3]
name: CrowdChat
category: company
url: crowdchat.ca
description: CrowdChat est une entreprise spécialisée dans la gestion et l'implémentation d’un clavardage en ligne ayant comme missions d’augmenter le nombre de rendez-vous et de ventes des entreprises sur leurs sites Web.
![crowdchat-logo](https://cloud.githubusercontent.com/assets/16294437/11791179/d80323aa-a26d-11e5-90b4-98555836bf72.jpg)

**Comment by allaire** [comment]
C'est ajouté @kmichaud !
